### ISSUE TITLE
ReferenceError: AppInfo is not defined

### ISSUE THREAD

**Issue by derwok** [jorisroling/meteor-app-info#1]
Great idea. Would love to use this!

With current meteor 1.3.2 I did:
-  meteor add jorisroling:app-info
- Add an empty AppInfo.info in the root of my app's sources (so above /client /server /lib directory).

Now, when I launch my app with 'meteor' I get:

```
W20160428-07:42:43.860(2)? (STDERR) ReferenceError: AppInfo is not defined
W20160428-07:42:43.860(2)? (STDERR)     at meteorInstall.AppInfo.info.js (AppInfo.info.js:1:1)
W20160428-07:42:43.860(2)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:141:1)
W20160428-07:42:43.860(2)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
W20160428-07:42:43.860(2)? (STDERR)     at /Users/wok/source/_js/4minutes/.meteor/local/build/programs/server/app/app.js:870:1
W20160428-07:42:43.861(2)? (STDERR)     at /Users/wok/source/_js/4minutes/.meteor/local/build/programs/server/boot.js:283:10
W20160428-07:42:43.861(2)? (STDERR)     at Array.forEach (native)
W20160428-07:42:43.861(2)? (STDERR)     at Function._.each._.forEach (/Users/wok/.meteor/packages/meteor-tool/.1.3.2_4.lbyo5v++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160428-07:42:43.861(2)? (STDERR)     at /Users/wok/source/_js/4minutes/.meteor/local/build/programs/server/boot.js:133:5
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.
```

Any idea how to fix this?

**Comment by jorisroling** [comment]
I am on holyday, will look into it when I'm back. Joris

**Comment by jorisroling** [comment]
I've fixed the issue, I think. Could you check?
